
#====================================注意：系统属性添加处==============================
server:
  port: 8080
  servlet:
    path: /cola

#spring
spring:
  datasource:
#    url: jdbc:sqlserver://localhost:1433;DatabaseName=my_sbm
    url: jdbc:sqlserver://139.219.193.48:1433;DatabaseName=BPRE
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: bpre
    password: bpre
    initial-size: 1
    min-idle: 1
    max-active: 20
    test-on-borrow: true
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-While-Idle: true
    test-on-return: false
    pool-prepared-statements: false
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall,log4j,config

#mybatis
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.coca.mapper
debug: true



